-- ============================================================================
-- Partner 360 · Ovation Medical — documents & videos (v2, incl. instruction sheets)
-- PDAC letters, IFU instruction PDFs, and product videos pulled from ovationmed.com.
-- Run once. Idempotent (full overwrite per product).
-- ============================================================================

update public.product_content set documents = '[{"title": "PDAC Coding Verification Letter (OA Knee)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/07/PDAC-Letter-OA-KNEE-67849939-CODING-VERIFICATION-1.pdf"}]'::jsonb, videos = '[{"title": "The Game Changer — Product Film", "url": "https://www.ovationmed.com/app/uploads/2023/09/Y2Mate.is-The-Game-Changer-Product-Film-Ovation-Medical-D75-AJ_8dD8-720p-1659815002306.mp4"}, {"title": "The Game Changer — Instructions for Use (IFU)", "url": "https://www.ovationmed.com/app/uploads/2023/07/TheGameChangerIFU.mp4"}, {"title": "Game Changer — Strap Application", "url": "https://www.ovationmed.com/app/uploads/2023/07/Game-Changer-Strap-Fin1-2-1-1.mp4"}]'::jsonb where manufacturer='ovation-medical' and page_key='game-changer-oa';
update public.product_content set documents = '[{"title": "PDAC Coding Verification Letter (L1902)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/07/Nu-Form-Ankle-Brace-25002-2X-L1902_08-05-2021-1.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='nu-form-ankle-brace';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/08/Compact-Pro-Post-op-Knee-Standard-Wrap-IFU.pdf"}, {"title": "PDAC Coding Letter — Standard (51500)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/07/Compact-Pro-Standard-Wrap-51500-L1832_L1833_04212021-1.pdf"}, {"title": "PDAC Coding Letter — X-Large (51508)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/07/Compact-Pro-Standard-Wrap-XL-51508-L1832_L1833_04212021-1.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='compact-pro-rom';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/09/Hybrid-Night-Splint-IFU.pdf"}]'::jsonb, videos = '[{"title": "Hybrid Night Splint — Demo", "url": "https://www.ovationmed.com/app/uploads/2023/09/hybridvideo2.mp4"}]'::jsonb where manufacturer='ovation-medical' and page_key='hybrid-night-splint';
update public.product_content set documents = '[{"title": "PDAC Coding Verification Letter (L3809)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/07/Nu-Form-VersaFit-Thumb-Spica-51075-5-L3809_08-05-2021.pdf"}]'::jsonb, videos = '[{"title": "Nu-Form & Versa-Fit Thumb Spica", "url": "https://www.ovationmed.com/app/uploads/2023/07/NuFormVersaFitThumbSpica.mp4"}]'::jsonb where manufacturer='ovation-medical' and page_key='thumb-spica';
update public.product_content set documents = '[{"title": "PDAC Coding Verification Letter (L0627, 62001)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/08/PDAC-NU-FORM-BACK-BRACE-V2-L0627-62001.pdf"}]'::jsonb, videos = '[{"title": "Nu-Form Universal Back Brace (L0627/L0642)", "url": "https://www.youtube.com/embed/1WO4s2XTD3s"}]'::jsonb where manufacturer='ovation-medical' and page_key='nu-form-back';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/09/V1-Back-Brace-IFU.pdf"}, {"title": "PDAC Coding Verification Letter — LS Double-Pull", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/08/PDAC-Letter-LS-Double-Pull.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='ls-double-pull-back';
update public.product_content set documents = '[{"title": "PDAC Coding Verification Letter (L3908)", "type": "other", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/07/Versa-Fit-Wrist-Brace-59075-2-L3908_08-05-2021-1.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='versa-fit-wrist';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/09/Universal-8-Wrist-Brace-IFU.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='universal-wrist';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/09/Arm-Sling-with-Padded-Shoulder-IFU.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='arm-sling';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/09/Shoulder-Abduction-Sling-IFU.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='shoulder-immobilizer';
update public.product_content set documents = '[{"title": "Instructions for Use (IFU)", "type": "instructions", "hosted": false, "url": "https://www.ovationmed.com/app/uploads/2023/09/Standard-Walking-Boot-IFU.pdf"}]'::jsonb, videos = '[]'::jsonb where manufacturer='ovation-medical' and page_key='gen2-walking-boot';
